# Generated by Django 3.0.4 on 2020-03-31 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('marks', models.CharField(default='0', max_length=10)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('urans', models.CharField(default='0', max_length=120)),
                ('student', models.CharField(default='0', max_length=120)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Topic.Topic')),
            ],
        ),
    ]
