# Generated by Django 3.0.4 on 2020-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=60),
        ),
    ]
