# Generated by Django 3.0.4 on 2020-03-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('average', 'average'), ('hard', 'hard')], default='average', max_length=7)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Topic.Topic')),
            ],
        ),
    ]
