# Generated by Django 3.0.4 on 2020-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
